### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by NuriaQueralt** [tkonopka/NetworkCurator#2] opened 2018-10-30 05:03 UTC
Hi!

I am trying to install the web app without success. All the installation process went without errors. But when requesting my website in a browser i got:

This site can’t be reached
XXXXXXX server IP address could not be found.

I am doing the installation on a local server associated with a public domain.  i have sudo privileges on the server.  my guess is that the problem comes from the settings i am specifying in `install-settings-local.php` or on the password i am associating with the siteadmin (that i am not sure if i am as a sudo user of the server?)

Any hint on how to trace what is the problem? Thanks!

**Comment by tkonopka** [comment] 2018-10-30 08:17
Hard to tell exactly, but it sounds like a configuration issue with the web server.

Can you confirm that the web server is working, i.e. that it can display simple html and php content in the browser? Next things to check might be permissions on the php files; they might need to be set to executable.

I don't think you need sudo access on the server. You said the installation went fine, so you have a database set up and created some records. That should be enough to run the whole thing.

**Comment by NuriaQueralt** [comment] 2018-10-31 04:07
I confirm you that the web server is working and that the problem is not related to executable permissions on the php files...

Yes i have a database set up with the created users for nc as specified in the installation process... 

i think is related to something in the local settings of the web service... what should be there related to siteadmin?  i don't know exaclty who is... or how to set it up... can you provide some reference/example  on how to set up?

**Comment by tkonopka** [comment] 2018-10-31 07:08
Thanks for confirming that. If the web server is working, it should be able to process at least part of `index.php` from the NetworkCurator repo. Could you try to investigate at which point the script is failing? Apologies for this low level debugging, but I'm not sure how else to diagnose the issue. 

Regarding the local settings - do you mean the `install-settings-local.php` file? You probably saw the example on the installation docs. You can send me your file or a mockup if you like. 

If you think the issue is with a configuration outside of the NetworkCurator code, I'm not sure I would be able to help much there, unfortunately.

**Comment by NuriaQueralt** [comment] 2018-11-01 00:09
Executing index.php in the shell i got these errors:

sudo php index.php 
PHP Notice:  Undefined index: REMOTE_ADDR in /var/www/html/index.php on line 57
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/nc-api/helpers/GeneralApiCaller.php:52
Stack trace:
#0 /var/www/html/nc-core/php/NCApiCaller.php(150): GeneralApiCaller->sendRequest(Array)
#1 /var/www/html/index.php(61): NCApiCaller->querySelfPermissions('')
#2 {main}
  thrown in /var/www/html/nc-api/helpers/GeneralApiCaller.php on line 52

**Comment by tkonopka** [comment] 2018-11-01 05:04
Thanks, that's informative. curl_init() comes from a separate php library and that might not be installed. The installation details for the library will be specific to your OS, system, and version of php, but there should be docs out there.

(Perhaps the NetworkCurator install procedure should check for this and give an installation error or warning.)

As an aside: script index.php expects to be called through a browser, so it is going to generate some errors if run from the shell. If it keeps giving messages after resolving the curl issue, that's ok, just try it again in the browser.

**Comment by tkonopka** [comment] 2018-11-06 20:19
Hey. Curious about the status of your installation. Did you overcome the curl error and does the software run?

**Closed as completed** 2018-11-12 20:50 UTC
